#!/usr/bin/env python3
# make_zero.py - rebuild the S3-Zero Webby sketch from the SuperMini one.
# The two dongles run the SAME firmware; only the status light differs (WEBBY_ZERO).
# Keeping a second sketch folder gives the Zero its own build output, so its merged .bin
# (Gotek_Zero_Webby.ino.merged.bin) never overwrites the SuperMini's.
# Never edit Gotek_Zero_Webby.ino by hand: edit ../Gotek_SuperMini_Webby/Gotek_SuperMini_Webby.ino, run this.
import pathlib, shutil, sys
here = pathlib.Path(__file__).resolve().parent
src_dir = here.parent / "Gotek_SuperMini_Webby"
src = (src_dir / "Gotek_SuperMini_Webby.ino").read_text(encoding="utf-8")
flag = "#define WEBBY_ZERO     0"
if src.count(flag) != 1:
    sys.exit("make_zero: the WEBBY_ZERO line was not found exactly once - nothing written")
banner = ("// ============================================================================\n"
          "// GENERATED by make_zero.py from ../Gotek_SuperMini_Webby/Gotek_SuperMini_Webby.ino\n"
          "// DO NOT EDIT HERE - edit the SuperMini sketch and run make_zero.py again.\n"
          "// Only difference: WEBBY_ZERO is 1 (Waveshare S3-Zero, WS2812 status LED on GPIO21).\n"
          "// ============================================================================\n")
out = banner + src.replace(flag, "#define WEBBY_ZERO     1")
(here / "Gotek_Zero_Webby.ino").write_text(out, encoding="utf-8", newline="")
shutil.copyfile(src_dir / "webui.h", here / "webui.h")
print("make_zero: Gotek_Zero_Webby.ino + webui.h written")
