#!/usr/bin/env python3
# make_xiao.py - rebuild the XIAO Webby sketch from the SuperMini one (as make_zero.py does for the Zero).
# The XIAO runs the SAME firmware as the SuperMini, LEDs included; only the board settings differ.
# Keeping its own sketch folder gives the XIAO its own build output, so its merged .bin
# (Gotek_XIAO_Webby.ino.merged.bin) never overwrites the SuperMini's.
# Never edit Gotek_XIAO_Webby.ino by hand: edit ../Gotek_SuperMini_Webby/Gotek_SuperMini_Webby.ino, run this.
import pathlib, shutil, sys
here = pathlib.Path(__file__).resolve().parent
src_dir = here.parent / "Gotek_SuperMini_Webby"
src = (src_dir / "Gotek_SuperMini_Webby.ino").read_text(encoding="utf-8")
flag = "#define WEBBY_XIAO     0"
if src.count(flag) != 1:
    sys.exit("make_xiao: the WEBBY_XIAO line was not found exactly once - nothing written")
banner = ("// ============================================================================\n"
          "// GENERATED by make_xiao.py from ../Gotek_SuperMini_Webby/Gotek_SuperMini_Webby.ino\n"
          "// DO NOT EDIT HERE - edit the SuperMini sketch and run make_xiao.py again.\n"
          "// Only difference: WEBBY_XIAO is 1 (Seeed XIAO ESP32-S3, S3R8: 8MB octal PSRAM, 8MB flash).\n"
          "// Board settings for THIS sketch (not the SuperMini's):\n"
          "//   ESP32S3 Dev Module, PSRAM: OPI, Flash Size: 8MB, Partition: 8M with spiffs (two app\n"
          "//   slots, so the web page's firmware update works), USB Mode: USB-OTG (TinyUSB),\n"
          "//   USB CDC on Boot: Disabled, MSC on Boot: Disabled, CPU: 240MHz.\n"
          "//   arduino-cli: esp32:esp32:esp32s3:FlashSize=8M,PSRAM=opi,PartitionScheme=default_8MB\n"
          "//   A QSPI build will not boot on this board.\n"
          "// ============================================================================\n")
out = banner + src.replace(flag, "#define WEBBY_XIAO     1")
(here / "Gotek_XIAO_Webby.ino").write_text(out, encoding="utf-8", newline="")
shutil.copyfile(src_dir / "webui.h", here / "webui.h")
print("make_xiao: Gotek_XIAO_Webby.ino + webui.h written")
